
import streamlit as st
import json
import pandas as pd
from io import StringIO
import datetime
import sqlite3
import os
import sys
import re
import base64
from pathlib import Path

# ============================================================================
# STANDARDIZED YOUTH REGISTRATION FORM APP WITH WAIVER INTEGRATION
# ============================================================================
# This app dynamically renders youth registration forms generated by app_copy_2.py
# and includes integrated waiver signing and storage.
# 
# USAGE:
# 1. Run app_copy_2.py with your event details (fully automated workflow)
# 2. form_app.py will automatically load the generated form from current_event_form.json
# 3. Waivers are automatically stored when participants sign
# 4. No manual copying needed!
# ============================================================================

# Import waiver function from app_copy_2
try:
    sys.path.insert(0, str(Path(__file__).parent))
    from app_copy_2 import save_signed_waiver
    WAIVER_ENABLED = True
except ImportError:
    WAIVER_ENABLED = False

# Load form from file (auto-generated by app_copy_2.py)
def load_form_schema():
    """Load form schema from current_event_form.json or query parameter."""
    import glob
    
    # Try multiple possible locations (local, subfolder, etc)
    possible_paths = [
        "current_event_form.json",
        "./current_event_form.json",
        "../current_event_form.json",
        "python-langchain/current_event_form.json",
    ]
    
    for form_file in possible_paths:
        if os.path.exists(form_file):
            try:
                with open(form_file, 'r') as f:
                    # Return form without displaying message (admin will see status in sidebar)
                    return json.load(f)
            except Exception as e:
                # Silent fail, will use default form
                pass
    
    # If no form file found, use default
    return get_default_form()

def get_default_form():
    """Fallback default form if no file exists."""
    return {
        "title": "Youth Event Registration Form",
        "description": "Register for our youth event. Please provide all required information.",
        "event_details": {
            "event_name": "Youth Event",
            "date": "TBD",
            "time": "TBD",
            "location": "TBD",
            "max_participants": 30,
            "age_range": "12-17"
        },
        "fields": [
            {"name": "youth_first_last_name", "label": "Youth First and Last Name", "type": "text", "required": True},
            {"name": "youth_age", "label": "Youth Age", "type": "number", "required": True},
            {"name": "parent_first_last_name", "label": "Parent/Guardian First and Last Name", "type": "text", "required": True},
            {"name": "parent_phone", "label": "Parent/Guardian Phone Number", "type": "tel", "required": True},
            {"name": "transportation_needed", "label": "Need transportation?", "type": "select", "required": True, "options": [{"label": "Yes", "value": "yes"}, {"label": "No", "value": "no"}]},
            {"name": "special_needs", "label": "Special accommodations? (If yes, specify)", "type": "textarea", "required": False},
            {"name": "consent", "label": "I give permission for my child to participate.", "type": "checkbox", "required": True},
            {"name": "signature", "label": "Parent/Guardian Signature", "type": "text", "required": True},
            {"name": "date", "label": "Date", "type": "date", "required": True}
        ]
    }

st.set_page_config(page_title="Registration Form", layout="wide")

# Admin password (can be overridden with env variable)
ADMIN_PASSWORD = os.getenv("FORM_APP_ADMIN_PASSWORD", "admin123")

# Initialize session state
if 'admin_authenticated' not in st.session_state:
    st.session_state['admin_authenticated'] = False
if 'show_admin_panel' not in st.session_state:
    st.session_state['show_admin_panel'] = False

# Automatically load form schema from file (or use default)
# TTL=60 means cache expires after 60 seconds (auto-refresh hosted app)
@st.cache_data(ttl=60)
def cached_load_form_schema():
    return load_form_schema()

form_data = cached_load_form_schema()

# Admin panel toggle in sidebar
with st.sidebar:
    st.markdown("---")


# Extract event details safely (with fallback defaults)
event_details = form_data.get("event_details", {})
event_name = event_details.get("event_name", "Youth Event Registration")
event_title = form_data.get("title", event_name)
event_description = form_data.get("description", "Register for our youth event.")

# Database name based on event (sanitized)
db_event_slug = "".join(c.lower() if c.isalnum() else "_" for c in event_name)[:30]
DB_PATH = f"registrations_{db_event_slug}.db"
TABLE_NAME = "registrations"

# Initialize session state for page navigation
if 'show_summary' not in st.session_state:
    st.session_state['show_summary'] = False
if 'submission_summary' not in st.session_state:
    st.session_state['submission_summary'] = None

# Show summary page if submission was successful
if st.session_state.get('show_summary', False):
    st.markdown(f"<h1 style='color: purple; text-align: center;'>Registration Submitted</h1>", unsafe_allow_html=True)
    st.success("🎉 Registration submitted successfully!")
    st.balloons()
    st.subheader("📄 Your Submission Summary")
    summary = st.session_state.get('submission_summary', {})
    if summary:
        # Display fields dynamically based on form schema
        for field in form_data.get("fields", []):
            field_name = field["name"]
            field_label = field["label"]
            field_value = summary.get(field_name, '')
            
            # Format display based on field type
            if field["type"] == "checkbox":
                display_value = "Yes" if field_value else "No"
            elif field["type"] == "date":
                display_value = str(field_value) if field_value else "—"
            else:
                display_value = str(field_value) if field_value else "—"
            
            st.markdown(f"**{field_label}:** {display_value}")
        
        # Waiver confirmation if applicable
        if summary.get('waiver_file_path'):
            st.markdown("---")
            st.success("✍️ **Waiver Signed & Stored**")
            st.caption(f"📁 Waiver record: `{summary['waiver_file_path']}`")
        
        # Event details summary
        if event_details:
            st.markdown("---")
            st.markdown("**Event Information:**")
            st.markdown(f"- **Event:** {event_name}")
            st.markdown(f"- **Date:** {event_details.get('date', 'TBD')}")
            st.markdown(f"- **Time:** {event_details.get('time', 'TBD')}")
            st.markdown(f"- **Location:** {event_details.get('location', 'TBD')}")
    
    # Option to return to form
    if st.button("⬅️ Register Another Child"):
        st.session_state['show_summary'] = False
        st.session_state['submission_summary'] = None
        st.rerun()
    st.stop()  # Stop execution here, don't show form

# Header with title
st.markdown(f"<h1 style='color: purple; text-align: center;'>{event_title}</h1>", unsafe_allow_html=True)

if "description" in form_data:
    st.write(form_data["description"])
else:
    st.info("📋 Fill out the form below to register.")

# Show registration count and capacity only to admin
if st.session_state.get('admin_authenticated'):
    try:
        reg_count = len(get_all_registrations())
        col1, col2, col3 = st.columns(3)
        with col1:
            st.metric("📝 Registrations", reg_count)
        with col2:
            st.metric("👥 Max Capacity", event_details.get('max_participants', 'N/A'))
        with col3:
            remaining = event_details.get('max_participants', 0) - reg_count if isinstance(event_details.get('max_participants'), int) else "N/A"
            st.metric("🔢 Spots Remaining", remaining)
    except:
        pass


# ============================================================================
# SQLite DATABASE SETUP (Dynamic based on event)
# ============================================================================

def get_db_connection():
    conn = sqlite3.connect(DB_PATH)
    return conn

def create_table_if_not_exists(fields, event_det):
    """Build dynamic SQL table based on form fields and event details."""
    # Filter out section headers (they don't have 'name' key)
    actual_fields = [f for f in fields if f.get('type') != 'section_header' and 'name' in f]
    
    # Build SQL for dynamic fields
    columns = [
        f"{f['name']} TEXT" if f["type"] not in ["number", "date", "checkbox"] else (
            f"{f['name']} INTEGER" if f["type"] == "number" else (
                f"{f['name']} BOOLEAN" if f["type"] == "checkbox" else f"{f['name']} TEXT"
            )
        )
        for f in actual_fields
    ]
    # Add metadata columns (timestamp + event details)
    columns += [
        "timestamp TEXT",
        "event_name TEXT",
        "event_date TEXT",
        "event_time TEXT",
        "event_location TEXT",
        "event_max_participants INTEGER",
        "event_age_range TEXT"
    ]
    sql = f"CREATE TABLE IF NOT EXISTS {TABLE_NAME} (id INTEGER PRIMARY KEY AUTOINCREMENT, {', '.join(columns)})"
    with get_db_connection() as conn:
        conn.execute(sql)
        conn.commit()

def insert_registration(submission):
    keys = list(submission.keys())
    values = [submission[k] for k in keys]
    placeholders = ",".join(["?" for _ in keys])
    sql = f"INSERT INTO {TABLE_NAME} ({', '.join(keys)}) VALUES ({placeholders})"
    with get_db_connection() as conn:
        conn.execute(sql, values)
        conn.commit()

def get_all_registrations():
    with get_db_connection() as conn:
        df = pd.read_sql_query(f"SELECT * FROM {TABLE_NAME}", conn)
    return df

def generate_csv_with_metadata(registrations_df, event_details):
    """Generate CSV export with event metadata header."""
    if registrations_df.empty:
        return None
    
    # Create StringIO object for CSV content
    csv_buffer = StringIO()
    
    # Add metadata header
    csv_buffer.write(f"Event Registration Export\n")
    csv_buffer.write(f"Event: {event_details.get('event_name', 'Unknown')}\n")
    csv_buffer.write(f"Date: {event_details.get('date', 'TBD')}\n")
    csv_buffer.write(f"Time: {event_details.get('time', 'TBD')}\n")
    csv_buffer.write(f"Location: {event_details.get('location', 'TBD')}\n")
    csv_buffer.write(f"Exported: {datetime.datetime.now().strftime('%B %d, %Y at %I:%M %p')}\n")
    csv_buffer.write(f"Total Registrations: {len(registrations_df)}\n")
    csv_buffer.write("\n")  # Blank line separator
    
    # Write the actual CSV data
    registrations_df.to_csv(csv_buffer, index=False)
    
    return csv_buffer.getvalue()

def setup_waiver_directory() -> str:
    """Create directory structure for storing waivers."""
    waivers_dir = os.path.join(os.path.dirname(__file__), "waivers")
    if not os.path.exists(waivers_dir):
        os.makedirs(waivers_dir)
    return waivers_dir

def process_waiver_submission(form_values, event_details):
    """Process and store waiver submission if waiver fields exist."""
    if not WAIVER_ENABLED:
        return None
    
    # Check if waiver fields exist in the form
    waiver_fields = ['waiver_acknowledgment', 'waiver_signature', 'waiver_date']
    has_waiver_fields = any(field in form_values for field in waiver_fields)
    
    if not has_waiver_fields:
        return None
    
    # Validate waiver acknowledgment
    if not form_values.get('waiver_acknowledgment', False):
        return {'status': 'error', 'message': '❌ You must acknowledge the waiver to continue'}
    
    # Ensure waiver signature is provided
    if not form_values.get('waiver_signature', '').strip():
        return {'status': 'error', 'message': '❌ Waiver signature is required'}
    
    try:
        # Save the signed waiver
        waiver_result = save_signed_waiver(
            participant_info=form_values,
            event_name=event_details.get('event_name', 'Unknown Event')
        )
        return {'status': 'success', 'result': waiver_result}
    except Exception as e:
        return {'status': 'error', 'message': f'❌ Error processing waiver: {str(e)}'}

# Create table if needed
create_table_if_not_exists(form_data.get("fields", []), event_details)

with st.form(key="youth_registration"):
    form_values = {}
    current_section = None
    fields_list = form_data.get("fields", [])
    
    for idx, field in enumerate(fields_list):
        # Handle section headers
        if field.get("type") == "section_header":
            st.divider()
            st.subheader(field.get("section", "Section"))
            current_section = field.get("section", "")
            
            # Display waiver PDF button right after the waiver section header
            if current_section and "WAIVER" in current_section.upper():
                if WAIVER_ENABLED:
                    waiver_pdf_path = os.path.join(os.path.dirname(__file__), "waivers", "Waiver.pdf")
                    if os.path.exists(waiver_pdf_path):
                        # Read and encode PDF as base64 for data URI
                        with open(waiver_pdf_path, "rb") as pdf_file:
                            pdf_data = pdf_file.read()
                            pdf_base64 = base64.b64encode(pdf_data).decode()
                        
                        # Display HTML download link styled as a button
                        st.markdown(f"""
                        <div style="display: flex; gap: 10px;">
                            <a href="data:application/pdf;base64,{pdf_base64}" download="Youth_Event_Waiver.pdf">
                                <button style="padding: 10px 20px; border: none; border-radius: 4px; background-color: #f0f2f6; cursor: pointer; font-size: 16px; width: 100%;">
                                    📄 View Full Waiver PDF
                                </button>
                            </a>
                        </div>
                        """, unsafe_allow_html=True)
            continue
        
        f_name = field["name"]
        f_label = field["label"]
        f_type = field.get("type", "text")
        f_required = field.get("required", False)
        
        # Update waiver checkbox label
        if f_name == "waiver_acknowledgment":
            f_label = "I have read and agree to the liability waiver"

        if f_type == "select":
            options = [opt.get("label", str(opt)) for opt in field.get("options", [])]
            form_values[f_name] = st.selectbox(f_label, options, key=f_name)
        elif f_type == "textarea":
            form_values[f_name] = st.text_area(f_label, key=f_name, height=100)
        elif f_type == "checkbox":
            form_values[f_name] = st.checkbox(f_label, key=f_name)
        elif f_type == "number":
            form_values[f_name] = st.number_input(f_label, min_value=0, max_value=100, step=1, key=f_name)
        elif f_type == "date":
            form_values[f_name] = st.date_input(f_label, value=datetime.date(2026, 4, 15), key=f_name, format="MM/DD/YYYY")
        elif f_type == "tel":
            form_values[f_name] = st.text_input(f_label, placeholder="(123) 456-7890", help="Phone format: (123) 456-7890", key=f_name)
        elif f_type == "email":
            form_values[f_name] = st.text_input(f_label, placeholder="name@example.com", type="default", key=f_name)
        else:  # text default
            form_values[f_name] = st.text_input(f_label, key=f_name)
    
    # Submit button OUTSIDE loop
    col1, col2 = st.columns([4, 1])
    with col2:
        submitted = st.form_submit_button("✅ Register", use_container_width=True)




if submitted:
    # Basic validation
    missing = [name for name, val in form_values.items() if not val and any(f.get("required") for f in form_data["fields"] if f["name"] == name)]
    if missing:
        st.error(f"❌ Required fields missing: {', '.join(missing)}")
    else:
        # Process waiver if integrated
        waiver_response = process_waiver_submission(form_values, event_details)
        if waiver_response and waiver_response['status'] == 'error':
            st.error(waiver_response['message'])
        else:
            # Create standardized submission with event metadata
            submission = {
                **form_values,
                "timestamp": datetime.datetime.now().isoformat(),
                "event_name": event_details.get("event_name", ""),
                "event_date": event_details.get("date", ""),
                "event_time": event_details.get("time", ""),
                "event_location": event_details.get("location", ""),
                "event_max_participants": event_details.get("max_participants", 0),
                "event_age_range": event_details.get("age_range", "")
            }
            insert_registration(submission)
            
            # Store waiver metadata in session if waiver was processed
            if waiver_response and waiver_response['status'] == 'success':
                submission['waiver_file_path'] = waiver_response['result'].get('file_path', '')
            
            st.session_state['submission_summary'] = submission
            st.session_state['show_summary'] = True
            st.rerun()




# Sidebar for event details (CUSTOMER) and admin dashboard (ADMIN)
with st.sidebar:
    st.header(event_name)
    
    # Display event details dynamically from form schema (CUSTOMER VIEW)
    if event_details:
        if "date" in event_details:
            st.write(f"📅 **Date:** {event_details.get('date', 'TBD')}")
        if "time" in event_details:
            st.write(f"⏰ **Time:** {event_details.get('time', 'TBD')}")
        if "location" in event_details:
            st.write(f"📍 **Location:** {event_details.get('location', 'TBD')}")
        if "age_range" in event_details:
            st.write(f"👥 **Age Range:** {event_details.get('age_range', 'All ages')}")
    else:
        st.info("No event details available")
    
    st.markdown("---")
    
    # Admin Panel Login
    if not st.session_state.get('admin_authenticated'):
        if st.button("🔐 Admin Panel", use_container_width=True):
            st.session_state['show_admin_panel'] = not st.session_state.get('show_admin_panel', False)
        
        if st.session_state.get('show_admin_panel'):
            st.warning("🔒 Admin Panel - Password Required")
            admin_password = st.text_input("Enter admin password:", type="password", key="admin_pwd")
            
            if admin_password:
                if admin_password == ADMIN_PASSWORD:
                    st.session_state['admin_authenticated'] = True
                    st.rerun()
                else:
                    st.error("❌ Incorrect password")
    else:
        # Show logout button if authenticated
        col1, col2 = st.columns(2)
        with col1:
            st.success("✅ Admin Mode")
        with col2:
            if st.button("🚪 Logout", use_container_width=True):
                st.session_state['admin_authenticated'] = False
                st.session_state['show_admin_panel'] = False
                st.rerun()
    
    st.markdown("---")
    if st.session_state.get('admin_authenticated'):
        # Show admin status and form loading info
        status_msg = f"✅ Form loaded from: current_event_form.json"
        if WAIVER_ENABLED:
            status_msg += " | ✍️ Waiver storage: ENABLED"
        else:
            status_msg += " | ✍️ Waiver storage: DISABLED"
        st.info(status_msg)
        st.subheader("📊 Admin Dashboard")
        
        # Registrations stats
        try:
            registrations_df = get_all_registrations()
            if not registrations_df.empty:
                col_stat1, col_stat2 = st.columns(2)
                with col_stat1:
                    st.metric("Total Registrations", len(registrations_df))
                with col_stat2:
                    max_cap = event_details.get('max_participants', 0)
                    if max_cap > 0:
                        pct = (len(registrations_df) / max_cap) * 100
                        st.metric("Capacity Used", f"{pct:.0f}%")
                
                # View registrations table
                with st.expander("📋 View All Registrations", expanded=False):
                    st.dataframe(registrations_df, use_container_width=True, height=400)
                
                # Export to CSV with event metadata
                csv_data = generate_csv_with_metadata(registrations_df, event_details)
                if csv_data:
                    # Create filename with event name and timestamp
                    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
                    event_slug = "".join(c.lower() if c.isalnum() else "_" for c in event_name)[:30]
                    csv_filename = f"registrations_{event_slug}_{timestamp}.csv"
                    
                    st.download_button(
                        label="📥 Download CSV",
                        data=csv_data,
                        file_name=csv_filename,
                        mime="text/csv",
                        use_container_width=True
                    )
                    
                    # Show info about the export
                    st.caption(f"📝 CSV includes event metadata and {len(registrations_df)} registrations")
            else:
                st.info("No registrations yet")
        except Exception as e:
            st.warning(f"Database error: {e}")
        
        st.markdown("---")
        st.caption(f"💾 Database: `{DB_PATH}`")
        if WAIVER_ENABLED:
            waivers_dir = os.path.join(os.path.dirname(__file__), "waivers")
            st.caption(f"📋 Waivers: `{waivers_dir}`")
    else:
        st.caption("🔐 Sign in as admin for analytics")
